### ISSUE TITLE
Automatic theming doesn't change the taskbar colors after waking up from sleep/hibernation

### ISSUE THREAD

**Issue by VincentJoshuaET** [AutoDarkMode/Windows-Auto-Night-Mode#47]
**Describe the bug**
As you can see in the screenshot, the taskbar color is not changed after waking up from sleep/hibernation then the automatic theme is triggered. The icon colors, the Start menu, the system, and the apps are changed correctly.

**To Reproduce**
1. Set laptop to sleep/hibernation
2. Turn it on
3. Auto Dark Mode automatically triggers the theme change
4.  (Only the) Taskbar color is not changed

**Expected behavior**
Taskbar should be white. (Or dark if the dark theme is triggered)

**Screenshots**
![Screenshot ](https://user-images.githubusercontent.com/19756326/62407326-1670a800-b5e9-11e9-82ea-fa1cd37871ac.png)

**Environment:**
 - OS Version: Windows 1903
 - Night-Mode Version 2.3
 - Has user admin rights? **Yes**
 - Which antivirus software you use? **Windows Defender**
 - What language is your Windows set to? **English**

**Additional context**

**Comment by Armin2208** [comment]
Thanks for reporting this issue.

You have battery saver enabled, or? It seems like a current windows bug.

**Comment by VincentJoshuaET** [comment]
I never have battery saver enabled. Thanks.

**Comment by Armin2208** [comment]
You never have? So this bug occurs on your machine still.

Does theme changing in  UWP settings work for you?

**Comment by VincentJoshuaET** [comment]
It only works only for changing the system and Apps theme. The taskbar color issue still occurs.

**Comment by VincentJoshuaET** [comment]
Can confirm this happens on both sleep and hibernate, but never on shutdown/restart. I have Fast Startup disabled.

**Comment by Armin2208** [comment]
What device do you use and what Windows edition?

**Comment by VincentJoshuaET** [comment]
Asus TUF FX505DY-AL026T Windows 10 1903 18362

**Comment by VincentJoshuaET** [comment]
This seems to be fixed for me on 20H1 builds. 18965 right now

**Comment by Armin2208** [comment]
Is it still fixed in the new 19002?

**Comment by tiadaguru** [comment]
I can confirm this exact same bug on 19H2 / 1909 (latest public build).  Even _**Windows**_ claims it is in the Light theme, but the taskbar remains black. Changing Windows light to dark manually does nothing to the taskbar.

It occurs between transitions: put laptop (in auto dark mode) to sleep at 3am + wake up laptop (in auto light mode) at 9am. The "auto light mode" is what's broken: at 9am now, the taskbar remains black (and thus even the Start menu is not really visible.

The original screenshot is exactly what I'm seeing.

Environment:

- OS Version: Windows 10 Pro x64 1909 (18363.752)
- Night-Mode Version 2.3.1
- Has user admin rights? Yes
- Which antivirus software you use? Avira
- What language is your Windows set to? English
- No power saving or battery mode

I unfortunately cannot test Insider builds in this system, but I am on the latest 1909 / 19H2 build and this bug occurs quite regularly (1-2 a week).

**Comment by ikjadoon** [comment]
I can confirm this exact same bug still exists on 19H2 / 1909 (latest public build). 

What I tried to do to fix it:

- Check Windows color settings. Windows says it is on the "Light" theme, but the taskbar is dark.
- Change Windows to Dark and then back to Light. Everything changes, but the taskar. It remains dark.

Reproduction steps match the OP exactly. To give it more clearly:

1. Put laptop to sleep when auto-dark has been activated (3 am).
2. Wake up laptop when auto-light bas been activated (9 am).
3. Taskbar should've turned light, but is now the only UI that remains dark in "Light" mode.

Thus even the Start menu icon is not really visible, i.e., the original screenshot is exactly what I'm seeing.

Environment:

- Device: HP Spectre x360 13t late 2019 (i7-1065G7)
- OS Version: Windows 10 Pro x64 1909 (18363.752)
- Night-Mode Version 2.3.1
- Has user admin rights? Yes
- Which antivirus software you use? Avira
- What language is your Windows set to? English
- **Battery saver is *disabled***

I unfortunately cannot test Insider builds in this system, but I am on the latest 1909 / 19H2 build and this bug occurs quite regularly (1-2 a week).

**Comment by Spiritreader** [comment]
this is now a baseline enabled-by-default functionality in Version X
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26

Please update, try it out and re-open the issue if it still isn't working. Thank you!
