### ISSUE TITLE
Changing background is not working

### ISSUE THREAD

**Issue by udobehm** [AutoDarkMode/Windows-Auto-Night-Mode#815]
### Description

Hi. For a while now switching the background image doesn't work anymore...

### Expected Behavior

The background image stays the same when the switch to dark or light mode occurs

### Log Data

[AutoDarkMode.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/14086934/AutoDarkMode.zip)

### Commit Hash, Version and Windows Build

- Commit: `cf7a0fe`
- Service/App: `10.4.1.1`
- Updater: `3.1.4`
- Shell: `1.3.3.0`
- .Net: `7.0.5`
- Windows: `22621.3007`

**Comment by Spiritreader** [comment]
should be fixed in beta.

**Comment by udobehm** [comment]
thx... hope it'll be released soon :)

**Comment by udobehm** [comment]
May I know when you will release the beta as stable version? I still have this problem here...

**Comment by Spiritreader** [comment]
> May I know when you will release the beta as stable version? I still have this problem here...

Do not ask for ETAs please.

**Comment by udobehm** [comment]
Ok, how do I install (and test) the beta?

**Comment by Armin2208** [comment]
Open Auto Dark Mode and go to settings, you will find a channel picker there.

**Comment by ovojake** [comment]
I can confirm that switching to beta fixed this issue for me just now.
